import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import { Show } from '@chakra-ui/react'
import Navbar from './navbar'
import Menu from './menu'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Show above='xl'>
            <Navbar />
          </Show>
          <Show below='xl'>
            <Menu />
          </Show>
          {children}
        </Providers>
      </body>
    </html>
  )
}
